### ISSUE TITLE
add newtype Pretty

### ISSUE THREAD

**Issue by yaitskov** [yav/pretty-show#47]
Hi,

```
newtype Pretty a = Pretty a deriving (Eq)

instance Show a => Show (Pretty a) where
  show (Pretty a) = ppShow $ show a

```

It would be useful for writing tests, because Hunit assertEqual prints ugly message for complex values.

**Comment by yav** [comment]
Thanks for the suggestion!  I just pushed a new version that has a newtype wrapper called `PPShow` give it a go, and let me know if it works as expected.  I used that name because `Pretty` is already used in another module in `pretty-show` and tends to be a popular class for pretty printing libraries so it is more likely to clash with stuff.

Btw, I assume you meant:
```haskell
instance Show a => Show (Pretty a) where
  show (Pretty a) = ppShow a
```

**Comment by yaitskov** [comment]
Thanks. Oh, you were right.
